matrix:
include:
  - os: linux
    dist: bionic
    sudo: true
    language: cpp

script:
  - swift build
  - swift test

before_install:
  - chmod ugo+x ./install.sh
  - . ./install.sh
  - git clone https://github.com/apple/sourcekit-lsp
  - cd sourcekit-lsp && swift build
